language: generic
sudo: required
services:
  - docker

before_install:
  # specify your docker image tag name i.e. -t myimagename
  - docker build -t matlau/docker-react -f Dockerfile.dev .

script:
  # reference your docker image tag name
  - docker run -e CI=true matlau/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-east-1" # AWS EB region
  app: "docker-react" # AWS EB app name
  env: "DockerReact-env" # AWS EB app anvironment name
  bucket_name: "elasticbeanstalk-us-east-1-830663695860" # AWS S3 bucket created for EB
  bucket_path: "docker-react" # AWS EB app name
  on:
    branch: master
